# Generated by Django 3.0.4 on 2020-03-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da localidade')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do motorista')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, verbose_name='Sexo')),
                ('cnh_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='Categoria da CNH')),
                ('owns_vehicle', models.BooleanField(default=False, verbose_name='Possui veículo')),
                ('is_loaded', models.BooleanField(default=False, verbose_name='Está carregado')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'CAMINHAO_3_4'), (2, 'CAMINHAO_TOCO'), (3, 'CAMINHAO_TRUCK'), (4, 'CARRETA_SIMPLES'), (5, 'CARRETA_EIXO_ESTENDIDO')], verbose_name='Tipo do caminhão')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_destiny', to='api.Location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_origin', to='api.Location')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
    ]
