# Generated by Django 3.0.4 on 2020-03-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localidade', 'verbose_name_plural': 'Localidades'},
        ),
    ]
