# Generated by Django 3.0.4 on 2020-03-08 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 19, 51, 39, 871617, tzinfo=utc), verbose_name='Data de registro'),
            preserve_default=False,
        ),
    ]
