# Generated by Django 3.0.4 on 2020-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200308_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'CAMINHAO_3_4'), (2, 'CAMINHAO_TOCO'), (3, 'CAMINHAO_TRUCK'), (4, 'CARRETA_SIMPLES'), (5, 'CARRETA_EIXO_ESTENDIDO')], verbose_name='Tipo do caminhão'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
